// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package samplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Notification_Status int32

const (
	Notification_UNKNOWN Notification_Status = 0
	Notification_UNREAD  Notification_Status = 1
	Notification_READ    Notification_Status = 2
)

var Notification_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "UNREAD",
	2: "READ",
}
var Notification_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"UNREAD":  1,
	"READ":    2,
}

func (x Notification_Status) String() string {
	return proto.EnumName(Notification_Status_name, int32(x))
}
func (Notification_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_data_3f6015a3a51532a5, []int{1, 0}
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_3f6015a3a51532a5, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Notification struct {
	Title                string              `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Body                 string              `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	Status               Notification_Status `protobuf:"varint,3,opt,name=status,enum=Notification_Status" json:"status,omitempty"`
	From                 *User               `protobuf:"bytes,4,opt,name=from" json:"from,omitempty"`
	To                   *User               `protobuf:"bytes,5,opt,name=to" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_3f6015a3a51532a5, []int{1}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Notification) GetStatus() Notification_Status {
	if m != nil {
		return m.Status
	}
	return Notification_UNKNOWN
}

func (m *Notification) GetFrom() *User {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Notification) GetTo() *User {
	if m != nil {
		return m.To
	}
	return nil
}

type Inbox struct {
	Notifications        []*Notification `protobuf:"bytes,1,rep,name=notifications" json:"notifications,omitempty"`
	UnreadNotifications  []*Notification `protobuf:"bytes,2,rep,name=unread_notifications,json=unreadNotifications" json:"unread_notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Inbox) Reset()         { *m = Inbox{} }
func (m *Inbox) String() string { return proto.CompactTextString(m) }
func (*Inbox) ProtoMessage()    {}
func (*Inbox) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_3f6015a3a51532a5, []int{2}
}
func (m *Inbox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inbox.Unmarshal(m, b)
}
func (m *Inbox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inbox.Marshal(b, m, deterministic)
}
func (dst *Inbox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inbox.Merge(dst, src)
}
func (m *Inbox) XXX_Size() int {
	return xxx_messageInfo_Inbox.Size(m)
}
func (m *Inbox) XXX_DiscardUnknown() {
	xxx_messageInfo_Inbox.DiscardUnknown(m)
}

var xxx_messageInfo_Inbox proto.InternalMessageInfo

func (m *Inbox) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *Inbox) GetUnreadNotifications() []*Notification {
	if m != nil {
		return m.UnreadNotifications
	}
	return nil
}

type SampleResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Inbox                *Inbox   `protobuf:"bytes,2,opt,name=inbox" json:"inbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleResponse) Reset()         { *m = SampleResponse{} }
func (m *SampleResponse) String() string { return proto.CompactTextString(m) }
func (*SampleResponse) ProtoMessage()    {}
func (*SampleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_3f6015a3a51532a5, []int{3}
}
func (m *SampleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleResponse.Unmarshal(m, b)
}
func (m *SampleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleResponse.Marshal(b, m, deterministic)
}
func (dst *SampleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleResponse.Merge(dst, src)
}
func (m *SampleResponse) XXX_Size() int {
	return xxx_messageInfo_SampleResponse.Size(m)
}
func (m *SampleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SampleResponse proto.InternalMessageInfo

func (m *SampleResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SampleResponse) GetInbox() *Inbox {
	if m != nil {
		return m.Inbox
	}
	return nil
}

type SampleRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	ShowUnread           bool     `protobuf:"varint,2,opt,name=show_unread,json=showUnread" json:"show_unread,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleRequest) Reset()         { *m = SampleRequest{} }
func (m *SampleRequest) String() string { return proto.CompactTextString(m) }
func (*SampleRequest) ProtoMessage()    {}
func (*SampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_3f6015a3a51532a5, []int{4}
}
func (m *SampleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleRequest.Unmarshal(m, b)
}
func (m *SampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleRequest.Marshal(b, m, deterministic)
}
func (dst *SampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleRequest.Merge(dst, src)
}
func (m *SampleRequest) XXX_Size() int {
	return xxx_messageInfo_SampleRequest.Size(m)
}
func (m *SampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SampleRequest proto.InternalMessageInfo

func (m *SampleRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SampleRequest) GetShowUnread() bool {
	if m != nil {
		return m.ShowUnread
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Notification)(nil), "Notification")
	proto.RegisterType((*Inbox)(nil), "Inbox")
	proto.RegisterType((*SampleResponse)(nil), "SampleResponse")
	proto.RegisterType((*SampleRequest)(nil), "SampleRequest")
	proto.RegisterEnum("Notification_Status", Notification_Status_name, Notification_Status_value)
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_3f6015a3a51532a5) }

var fileDescriptor_data_3f6015a3a51532a5 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x4b, 0xe3, 0x40,
	0x18, 0xdd, 0xa4, 0x49, 0x36, 0xfb, 0x65, 0x5b, 0xca, 0xb7, 0x5d, 0x88, 0x22, 0x18, 0x72, 0x0a,
	0x28, 0x39, 0xa4, 0x17, 0x8f, 0x2a, 0x2a, 0x14, 0x21, 0xc2, 0x94, 0x20, 0x78, 0x29, 0x13, 0x3b,
	0xc5, 0x60, 0x93, 0x89, 0x99, 0x09, 0xea, 0xc5, 0x7f, 0xe7, 0xff, 0x92, 0x99, 0xb4, 0x35, 0x05,
	0x6f, 0xf3, 0xde, 0xf7, 0xde, 0xe3, 0xcd, 0x37, 0x03, 0xb0, 0xa4, 0x92, 0xc6, 0x75, 0xc3, 0x25,
	0x0f, 0xcf, 0xc0, 0xca, 0x04, 0x6b, 0xf0, 0x10, 0xdc, 0x56, 0xb0, 0xa6, 0xa2, 0x25, 0xf3, 0x8d,
	0xc0, 0x88, 0xfe, 0x90, 0x1d, 0xc6, 0x09, 0xd8, 0xac, 0xa4, 0xc5, 0xda, 0x37, 0xf5, 0xa0, 0x03,
	0xe1, 0xa7, 0x01, 0x7f, 0x53, 0x2e, 0x8b, 0x55, 0xf1, 0x48, 0x65, 0xc1, 0x2b, 0x25, 0x93, 0x85,
	0x5c, 0x6f, 0xfd, 0x1d, 0x40, 0x04, 0x2b, 0xe7, 0xcb, 0xf7, 0x8d, 0x57, 0x9f, 0xf1, 0x14, 0x1c,
	0x21, 0xa9, 0x6c, 0x85, 0x3f, 0x08, 0x8c, 0x68, 0x94, 0x4c, 0xe2, 0x7e, 0x50, 0x3c, 0xd7, 0x33,
	0xb2, 0xd1, 0xe0, 0x01, 0x58, 0xab, 0x86, 0x97, 0xbe, 0x15, 0x18, 0x91, 0x97, 0xd8, 0xb1, 0xea,
	0x4b, 0x34, 0x85, 0xff, 0xc1, 0x94, 0xdc, 0xb7, 0xfb, 0x03, 0x53, 0xf2, 0xf0, 0x04, 0x9c, 0x2e,
	0x03, 0x3d, 0xf8, 0x9d, 0xa5, 0xb7, 0xe9, 0xdd, 0x7d, 0x3a, 0xfe, 0x85, 0x00, 0x4e, 0x96, 0x92,
	0xeb, 0x8b, 0xab, 0xb1, 0x81, 0x2e, 0x58, 0xfa, 0x64, 0x86, 0x1f, 0x60, 0xcf, 0xaa, 0x9c, 0xbf,
	0xe1, 0x14, 0x86, 0x55, 0xaf, 0x86, 0xf0, 0x8d, 0x60, 0x10, 0x79, 0xc9, 0x70, 0xaf, 0x1c, 0xd9,
	0xd7, 0xe0, 0x39, 0x4c, 0xda, 0xaa, 0x61, 0x74, 0xb9, 0xd8, 0xf7, 0x9a, 0x3f, 0x79, 0xff, 0x75,
	0xd2, 0x3e, 0x27, 0xc2, 0x19, 0x8c, 0xe6, 0xb4, 0xac, 0xd7, 0x8c, 0x30, 0x51, 0xf3, 0x4a, 0x30,
	0x75, 0x61, 0xb5, 0x7b, 0xbd, 0xc7, 0xef, 0x0b, 0x2b, 0x0a, 0x8f, 0xc0, 0x2e, 0x54, 0x59, 0xbd,
	0x4e, 0x2f, 0x71, 0x62, 0x5d, 0x9d, 0x74, 0x64, 0x78, 0x03, 0xc3, 0x6d, 0xd4, 0x4b, 0xcb, 0x84,
	0xd4, 0x4f, 0xc2, 0x9f, 0x59, 0xb5, 0x7b, 0x12, 0x05, 0xf0, 0x18, 0x3c, 0xf1, 0xc4, 0x5f, 0x17,
	0x5d, 0x1b, 0x1d, 0xe5, 0x12, 0x50, 0x54, 0xa6, 0x99, 0x4b, 0x78, 0x70, 0x85, 0xce, 0xa9, 0xf3,
	0xdc, 0xd1, 0xff, 0x64, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0x10, 0xaa, 0x85, 0xb0, 0x35, 0x02,
	0x00, 0x00,
}
